/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
  InternalInterfaceHandlerGetMeResponse
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the current authenticated user's information
 * @summary Get current user
 */
export const getApiV1UsersMe = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerGetMeResponse>(
      {url: `/api/v1/users/me`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV1UsersMeQueryKey = () => {
    return [`/api/v1/users/me`] as const;
    }

    
export const getGetApiV1UsersMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1UsersMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1UsersMe>>> = ({ signal }) => getApiV1UsersMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiV1UsersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1UsersMe>>>
export type GetApiV1UsersMeQueryError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse


/**
 * @summary Get current user
 */

export function useGetApiV1UsersMe<TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiV1UsersMeQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get current user
 */
export const prefetchGetApiV1UsersMeQuery = async <TData = Awaited<ReturnType<typeof getApiV1UsersMe>>, TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse>(
 queryClient: QueryClient,  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV1UsersMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}


