// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Test is the predicate function for test builders.
type Test func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)
