// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/keu-5/muzee/backend/config"
	"github.com/keu-5/muzee/backend/internal/database"
	"github.com/keu-5/muzee/backend/internal/handler"
	"github.com/keu-5/muzee/backend/internal/repository"
	"github.com/keu-5/muzee/backend/internal/service"
)

// Injectors from wire.go:

// InitializeApp initializes the entire application with all dependencies
func InitializeApp(cfg *config.Config) (*handler.Handler, error) {
	client, err := database.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client)
	authService := service.NewAuthService(userRepository, cfg)
	handlerHandler := handler.NewHandler(authService, cfg)
	return handlerHandler, nil
}
