/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTests500,
  InternalInterfaceHandlerTestResponse,
  PostTests500
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns all test records
 * @summary List all tests
 */
export const getTests = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerTestResponse[]>(
      {url: `/tests`, method: 'GET', signal
    },
      options);
    }
  

export const getGetTestsQueryKey = () => {
    return [`/tests`] as const;
    }

    
export const getGetTestsQueryOptions = <TData = Awaited<ReturnType<typeof getTests>>, TError = GetTests500>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTests>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTestsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTests>>> = ({ signal }) => getTests(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTests>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTestsQueryResult = NonNullable<Awaited<ReturnType<typeof getTests>>>
export type GetTestsQueryError = GetTests500


/**
 * @summary List all tests
 */

export function useGetTests<TData = Awaited<ReturnType<typeof getTests>>, TError = GetTests500>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTests>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTestsQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all tests
 */
export const prefetchGetTestsQuery = async <TData = Awaited<ReturnType<typeof getTests>>, TError = GetTests500>(
 queryClient: QueryClient,  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTests>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetTestsQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}


/**
 * Creates a test record and returns it
 * @summary Create a new test
 */
export const postTests = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerTestResponse>(
      {url: `/tests`, method: 'POST', signal
    },
      options);
    }
  


export const getPostTestsMutationOptions = <TError = PostTests500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTests>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postTests>>, TError,void, TContext> => {

const mutationKey = ['postTests'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTests>>, void> = () => {
          

          return  postTests(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostTestsMutationResult = NonNullable<Awaited<ReturnType<typeof postTests>>>
    
    export type PostTestsMutationError = PostTests500

    /**
 * @summary Create a new test
 */
export const usePostTests = <TError = PostTests500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTests>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postTests>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostTestsMutationOptions(options);

      return useMutation(mutationOptions );
    }
    