/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
  InternalInterfaceHandlerLoginRequest,
  InternalInterfaceHandlerLoginResponse,
  InternalInterfaceHandlerLogoutRequest,
  InternalInterfaceHandlerLogoutResponse,
  InternalInterfaceHandlerRefreshTokenRequest,
  InternalInterfaceHandlerRefreshTokenResponse,
  InternalInterfaceHandlerResendCodeRequest,
  InternalInterfaceHandlerResendCodeResponse,
  InternalInterfaceHandlerSendCodeRequest,
  InternalInterfaceHandlerSendCodeResponse,
  InternalInterfaceHandlerVerifyCodeRequest,
  InternalInterfaceHandlerVerifyCodeResponse
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Authenticates user with email and password. Returns tokens in JSON for mobile clients, and sets HttpOnly cookies for web browsers. Requires client_id for session tracking.
 * @summary User login
 */
export const postV1AuthLogin = (
    internalInterfaceHandlerLoginRequest: InternalInterfaceHandlerLoginRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerLoginResponse>(
      {url: `/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerLoginRequest, signal
    },
      options);
    }
  


export const getPostV1AuthLoginMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: InternalInterfaceHandlerLoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: InternalInterfaceHandlerLoginRequest}, TContext> => {

const mutationKey = ['postV1AuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogin>>, {data: InternalInterfaceHandlerLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogin>>>
    export type PostV1AuthLoginMutationBody = InternalInterfaceHandlerLoginRequest
    export type PostV1AuthLoginMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary User login
 */
export const usePostV1AuthLogin = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: InternalInterfaceHandlerLoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogin>>,
        TError,
        {data: InternalInterfaceHandlerLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostV1AuthLoginMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Invalidates the refresh token and ends the user's session. Accepts refresh token from either HttpOnly cookie (web) or request body (mobile). Also clears cookies for web browsers.
 * @summary User logout
 */
export const postV1AuthLogout = (
    internalInterfaceHandlerLogoutRequest: InternalInterfaceHandlerLogoutRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerLogoutResponse>(
      {url: `/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerLogoutRequest, signal
    },
      options);
    }
  


export const getPostV1AuthLogoutMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,{data: InternalInterfaceHandlerLogoutRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,{data: InternalInterfaceHandlerLogoutRequest}, TContext> => {

const mutationKey = ['postV1AuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogout>>, {data: InternalInterfaceHandlerLogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthLogout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogout>>>
    export type PostV1AuthLogoutMutationBody = InternalInterfaceHandlerLogoutRequest
    export type PostV1AuthLogoutMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary User logout
 */
export const usePostV1AuthLogout = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,{data: InternalInterfaceHandlerLogoutRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogout>>,
        TError,
        {data: InternalInterfaceHandlerLogoutRequest},
        TContext
      > => {

      const mutationOptions = getPostV1AuthLogoutMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Generates new access and refresh tokens. Accepts refresh token from either HttpOnly cookie (web) or request body (mobile). The old refresh token is invalidated. Requires client_id for session validation.
 * @summary Refresh access token
 */
export const postV1AuthRefresh = (
    internalInterfaceHandlerRefreshTokenRequest: InternalInterfaceHandlerRefreshTokenRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerRefreshTokenResponse>(
      {url: `/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerRefreshTokenRequest, signal
    },
      options);
    }
  


export const getPostV1AuthRefreshMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthRefresh>>, TError,{data: InternalInterfaceHandlerRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthRefresh>>, TError,{data: InternalInterfaceHandlerRefreshTokenRequest}, TContext> => {

const mutationKey = ['postV1AuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthRefresh>>, {data: InternalInterfaceHandlerRefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthRefresh>>>
    export type PostV1AuthRefreshMutationBody = InternalInterfaceHandlerRefreshTokenRequest
    export type PostV1AuthRefreshMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Refresh access token
 */
export const usePostV1AuthRefresh = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthRefresh>>, TError,{data: InternalInterfaceHandlerRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthRefresh>>,
        TError,
        {data: InternalInterfaceHandlerRefreshTokenRequest},
        TContext
      > => {

      const mutationOptions = getPostV1AuthRefreshMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Resends a new 6-digit verification code to the email for signup
 * @summary Resend verification code
 */
export const postV1AuthSignupResendCode = (
    internalInterfaceHandlerResendCodeRequest: InternalInterfaceHandlerResendCodeRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerResendCodeResponse>(
      {url: `/v1/auth/signup/resend-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerResendCodeRequest, signal
    },
      options);
    }
  


export const getPostV1AuthSignupResendCodeMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupResendCode>>, TError,{data: InternalInterfaceHandlerResendCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupResendCode>>, TError,{data: InternalInterfaceHandlerResendCodeRequest}, TContext> => {

const mutationKey = ['postV1AuthSignupResendCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthSignupResendCode>>, {data: InternalInterfaceHandlerResendCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthSignupResendCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthSignupResendCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthSignupResendCode>>>
    export type PostV1AuthSignupResendCodeMutationBody = InternalInterfaceHandlerResendCodeRequest
    export type PostV1AuthSignupResendCodeMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Resend verification code
 */
export const usePostV1AuthSignupResendCode = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupResendCode>>, TError,{data: InternalInterfaceHandlerResendCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthSignupResendCode>>,
        TError,
        {data: InternalInterfaceHandlerResendCodeRequest},
        TContext
      > => {

      const mutationOptions = getPostV1AuthSignupResendCodeMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Sends a 6-digit verification code to the email for signup
 * @summary Send verification code
 */
export const postV1AuthSignupSendCode = (
    internalInterfaceHandlerSendCodeRequest: InternalInterfaceHandlerSendCodeRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerSendCodeResponse>(
      {url: `/v1/auth/signup/send-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerSendCodeRequest, signal
    },
      options);
    }
  


export const getPostV1AuthSignupSendCodeMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupSendCode>>, TError,{data: InternalInterfaceHandlerSendCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupSendCode>>, TError,{data: InternalInterfaceHandlerSendCodeRequest}, TContext> => {

const mutationKey = ['postV1AuthSignupSendCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthSignupSendCode>>, {data: InternalInterfaceHandlerSendCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthSignupSendCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthSignupSendCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthSignupSendCode>>>
    export type PostV1AuthSignupSendCodeMutationBody = InternalInterfaceHandlerSendCodeRequest
    export type PostV1AuthSignupSendCodeMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Send verification code
 */
export const usePostV1AuthSignupSendCode = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupSendCode>>, TError,{data: InternalInterfaceHandlerSendCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthSignupSendCode>>,
        TError,
        {data: InternalInterfaceHandlerSendCodeRequest},
        TContext
      > => {

      const mutationOptions = getPostV1AuthSignupSendCodeMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Verifies the 6-digit code and creates a user account. Returns tokens in JSON for mobile clients, and sets HttpOnly cookies for web browsers. Requires client_id for session tracking.
 * @summary Verify code and create account
 */
export const postV1AuthSignupVerifyCode = (
    internalInterfaceHandlerVerifyCodeRequest: InternalInterfaceHandlerVerifyCodeRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerVerifyCodeResponse>(
      {url: `/v1/auth/signup/verify-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerVerifyCodeRequest, signal
    },
      options);
    }
  


export const getPostV1AuthSignupVerifyCodeMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupVerifyCode>>, TError,{data: InternalInterfaceHandlerVerifyCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupVerifyCode>>, TError,{data: InternalInterfaceHandlerVerifyCodeRequest}, TContext> => {

const mutationKey = ['postV1AuthSignupVerifyCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthSignupVerifyCode>>, {data: InternalInterfaceHandlerVerifyCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthSignupVerifyCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthSignupVerifyCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthSignupVerifyCode>>>
    export type PostV1AuthSignupVerifyCodeMutationBody = InternalInterfaceHandlerVerifyCodeRequest
    export type PostV1AuthSignupVerifyCodeMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Verify code and create account
 */
export const usePostV1AuthSignupVerifyCode = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthSignupVerifyCode>>, TError,{data: InternalInterfaceHandlerVerifyCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthSignupVerifyCode>>,
        TError,
        {data: InternalInterfaceHandlerVerifyCodeRequest},
        TContext
      > => {

      const mutationOptions = getPostV1AuthSignupVerifyCodeMutationOptions(options);

      return useMutation(mutationOptions );
    }
    