/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
  InternalInterfaceHandlerLoginRequest,
  InternalInterfaceHandlerLoginResponse,
  InternalInterfaceHandlerLogoutRequest,
  InternalInterfaceHandlerLogoutResponse,
  InternalInterfaceHandlerRefreshTokenRequest,
  InternalInterfaceHandlerRefreshTokenResponse,
  InternalInterfaceHandlerSendCodeRequest,
  InternalInterfaceHandlerSendCodeResponse,
  InternalInterfaceHandlerVerifyCodeRequest,
  InternalInterfaceHandlerVerifyCodeResponse
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Authenticates user with email and password, returns access and refresh tokens
 * @summary User login
 */
export const postApiV1AuthLogin = (
    internalInterfaceHandlerLoginRequest: InternalInterfaceHandlerLoginRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerLoginResponse>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerLoginRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthLoginMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: InternalInterfaceHandlerLoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: InternalInterfaceHandlerLoginRequest}, TContext> => {

const mutationKey = ['postApiV1AuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthLogin>>, {data: InternalInterfaceHandlerLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthLogin>>>
    export type PostApiV1AuthLoginMutationBody = InternalInterfaceHandlerLoginRequest
    export type PostApiV1AuthLoginMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary User login
 */
export const usePostApiV1AuthLogin = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogin>>, TError,{data: InternalInterfaceHandlerLoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthLogin>>,
        TError,
        {data: InternalInterfaceHandlerLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthLoginMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Invalidates the refresh token by deleting it from Redis, ending the user's session
 * @summary User logout
 */
export const postApiV1AuthLogout = (
    internalInterfaceHandlerLogoutRequest: InternalInterfaceHandlerLogoutRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerLogoutResponse>(
      {url: `/api/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerLogoutRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthLogoutMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,{data: InternalInterfaceHandlerLogoutRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,{data: InternalInterfaceHandlerLogoutRequest}, TContext> => {

const mutationKey = ['postApiV1AuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthLogout>>, {data: InternalInterfaceHandlerLogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthLogout(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthLogout>>>
    export type PostApiV1AuthLogoutMutationBody = InternalInterfaceHandlerLogoutRequest
    export type PostApiV1AuthLogoutMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary User logout
 */
export const usePostApiV1AuthLogout = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthLogout>>, TError,{data: InternalInterfaceHandlerLogoutRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthLogout>>,
        TError,
        {data: InternalInterfaceHandlerLogoutRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthLogoutMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Uses a refresh token to generate a new access token and refresh token. The old refresh token is invalidated.
 * @summary Refresh access token
 */
export const postApiV1AuthRefresh = (
    internalInterfaceHandlerRefreshTokenRequest: InternalInterfaceHandlerRefreshTokenRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerRefreshTokenResponse>(
      {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerRefreshTokenRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthRefreshMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, TError,{data: InternalInterfaceHandlerRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, TError,{data: InternalInterfaceHandlerRefreshTokenRequest}, TContext> => {

const mutationKey = ['postApiV1AuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, {data: InternalInterfaceHandlerRefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthRefresh(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthRefresh>>>
    export type PostApiV1AuthRefreshMutationBody = InternalInterfaceHandlerRefreshTokenRequest
    export type PostApiV1AuthRefreshMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Refresh access token
 */
export const usePostApiV1AuthRefresh = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthRefresh>>, TError,{data: InternalInterfaceHandlerRefreshTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthRefresh>>,
        TError,
        {data: InternalInterfaceHandlerRefreshTokenRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthRefreshMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Sends a 6-digit verification code to the email for signup
 * @summary Send verification code
 */
export const postApiV1AuthSignupSendCode = (
    internalInterfaceHandlerSendCodeRequest: InternalInterfaceHandlerSendCodeRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerSendCodeResponse>(
      {url: `/api/v1/auth/signup/send-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerSendCodeRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthSignupSendCodeMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthSignupSendCode>>, TError,{data: InternalInterfaceHandlerSendCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthSignupSendCode>>, TError,{data: InternalInterfaceHandlerSendCodeRequest}, TContext> => {

const mutationKey = ['postApiV1AuthSignupSendCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthSignupSendCode>>, {data: InternalInterfaceHandlerSendCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthSignupSendCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthSignupSendCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthSignupSendCode>>>
    export type PostApiV1AuthSignupSendCodeMutationBody = InternalInterfaceHandlerSendCodeRequest
    export type PostApiV1AuthSignupSendCodeMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Send verification code
 */
export const usePostApiV1AuthSignupSendCode = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthSignupSendCode>>, TError,{data: InternalInterfaceHandlerSendCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthSignupSendCode>>,
        TError,
        {data: InternalInterfaceHandlerSendCodeRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthSignupSendCodeMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Verifies the 6-digit code and creates a user account, returning access and refresh tokens
 * @summary Verify code and create account
 */
export const postApiV1AuthSignupVerifyCode = (
    internalInterfaceHandlerVerifyCodeRequest: InternalInterfaceHandlerVerifyCodeRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerVerifyCodeResponse>(
      {url: `/api/v1/auth/signup/verify-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerVerifyCodeRequest, signal
    },
      options);
    }
  


export const getPostApiV1AuthSignupVerifyCodeMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthSignupVerifyCode>>, TError,{data: InternalInterfaceHandlerVerifyCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthSignupVerifyCode>>, TError,{data: InternalInterfaceHandlerVerifyCodeRequest}, TContext> => {

const mutationKey = ['postApiV1AuthSignupVerifyCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AuthSignupVerifyCode>>, {data: InternalInterfaceHandlerVerifyCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AuthSignupVerifyCode(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AuthSignupVerifyCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AuthSignupVerifyCode>>>
    export type PostApiV1AuthSignupVerifyCodeMutationBody = InternalInterfaceHandlerVerifyCodeRequest
    export type PostApiV1AuthSignupVerifyCodeMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Verify code and create account
 */
export const usePostApiV1AuthSignupVerifyCode = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AuthSignupVerifyCode>>, TError,{data: InternalInterfaceHandlerVerifyCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AuthSignupVerifyCode>>,
        TError,
        {data: InternalInterfaceHandlerVerifyCodeRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1AuthSignupVerifyCodeMutationOptions(options);

      return useMutation(mutationOptions );
    }
    