// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keu-5/muzee/backend/ent/image"
	"github.com/keu-5/muzee/backend/ent/post"
	"github.com/keu-5/muzee/backend/ent/predicate"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *ImageUpdate) SetPostID(v int64) *ImageUpdate {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ImageUpdate) SetNillablePostID(v *int64) *ImageUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ImageUpdate) SetDisplayOrder(v int8) *ImageUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableDisplayOrder(v *int8) *ImageUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ImageUpdate) AddDisplayOrder(v int8) *ImageUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *ImageUpdate) SetAltText(v string) *ImageUpdate {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableAltText(v *string) *ImageUpdate {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// ClearAltText clears the value of the "alt_text" field.
func (_u *ImageUpdate) ClearAltText() *ImageUpdate {
	_u.mutation.ClearAltText()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageUpdate) SetUpdatedAt(v time.Time) *ImageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *ImageUpdate) SetPost(v *Post) *ImageUpdate {
	return _u.SetPostID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdate) Mutation() *ImageMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *ImageUpdate) ClearPost() *ImageUpdate {
	_u.mutation.ClearPost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := image.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageUpdate) check() error {
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := image.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "Image.display_order": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Image.post"`)
	}
	return nil
}

func (_u *ImageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(image.FieldDisplayOrder, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(image.FieldDisplayOrder, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(image.FieldAltText, field.TypeString, value)
	}
	if _u.mutation.AltTextCleared() {
		_spec.ClearField(image.FieldAltText, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(image.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.PostTable,
			Columns: []string{image.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.PostTable,
			Columns: []string{image.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetPostID sets the "post_id" field.
func (_u *ImageUpdateOne) SetPostID(v int64) *ImageUpdateOne {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillablePostID(v *int64) *ImageUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ImageUpdateOne) SetDisplayOrder(v int8) *ImageUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableDisplayOrder(v *int8) *ImageUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ImageUpdateOne) AddDisplayOrder(v int8) *ImageUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *ImageUpdateOne) SetAltText(v string) *ImageUpdateOne {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableAltText(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// ClearAltText clears the value of the "alt_text" field.
func (_u *ImageUpdateOne) ClearAltText() *ImageUpdateOne {
	_u.mutation.ClearAltText()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageUpdateOne) SetUpdatedAt(v time.Time) *ImageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *ImageUpdateOne) SetPost(v *Post) *ImageUpdateOne {
	return _u.SetPostID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdateOne) Mutation() *ImageMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *ImageUpdateOne) ClearPost() *ImageUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Image entity.
func (_u *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := image.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayOrder(); ok {
		if err := image.DisplayOrderValidator(v); err != nil {
			return &ValidationError{Name: "display_order", err: fmt.Errorf(`ent: validator failed for field "Image.display_order": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Image.post"`)
	}
	return nil
}

func (_u *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(image.FieldDisplayOrder, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(image.FieldDisplayOrder, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(image.FieldAltText, field.TypeString, value)
	}
	if _u.mutation.AltTextCleared() {
		_spec.ClearField(image.FieldAltText, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(image.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.PostTable,
			Columns: []string{image.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.PostTable,
			Columns: []string{image.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Image{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
