// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keu-5/muzee/backend/ent/image"
	"github.com/keu-5/muzee/backend/ent/like"
	"github.com/keu-5/muzee/backend/ent/post"
	"github.com/keu-5/muzee/backend/ent/user"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PostCreate) SetUserID(v int64) *PostCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRecommendedPostID sets the "recommended_post_id" field.
func (_c *PostCreate) SetRecommendedPostID(v int64) *PostCreate {
	_c.mutation.SetRecommendedPostID(v)
	return _c
}

// SetNillableRecommendedPostID sets the "recommended_post_id" field if the given value is not nil.
func (_c *PostCreate) SetNillableRecommendedPostID(v *int64) *PostCreate {
	if v != nil {
		_c.SetRecommendedPostID(*v)
	}
	return _c
}

// SetCaption sets the "caption" field.
func (_c *PostCreate) SetCaption(v string) *PostCreate {
	_c.mutation.SetCaption(v)
	return _c
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_c *PostCreate) SetNillableCaption(v *string) *PostCreate {
	if v != nil {
		_c.SetCaption(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *PostCreate) SetIsPublic(v bool) *PostCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *PostCreate) SetNillableIsPublic(v *bool) *PostCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetIsNsfw sets the "is_nsfw" field.
func (_c *PostCreate) SetIsNsfw(v bool) *PostCreate {
	_c.mutation.SetIsNsfw(v)
	return _c
}

// SetNillableIsNsfw sets the "is_nsfw" field if the given value is not nil.
func (_c *PostCreate) SetNillableIsNsfw(v *bool) *PostCreate {
	if v != nil {
		_c.SetIsNsfw(*v)
	}
	return _c
}

// SetLikedCount sets the "liked_count" field.
func (_c *PostCreate) SetLikedCount(v int) *PostCreate {
	_c.mutation.SetLikedCount(v)
	return _c
}

// SetNillableLikedCount sets the "liked_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableLikedCount(v *int) *PostCreate {
	if v != nil {
		_c.SetLikedCount(*v)
	}
	return _c
}

// SetRecommendedCount sets the "recommended_count" field.
func (_c *PostCreate) SetRecommendedCount(v int) *PostCreate {
	_c.mutation.SetRecommendedCount(v)
	return _c
}

// SetNillableRecommendedCount sets the "recommended_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableRecommendedCount(v *int) *PostCreate {
	if v != nil {
		_c.SetRecommendedCount(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PostCreate) SetViewCount(v int) *PostCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableViewCount(v *int) *PostCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v int64) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PostCreate) SetUser(v *User) *PostCreate {
	return _c.SetUserID(v.ID)
}

// AddRecommendingPostIDs adds the "recommending_posts" edge to the Post entity by IDs.
func (_c *PostCreate) AddRecommendingPostIDs(ids ...int64) *PostCreate {
	_c.mutation.AddRecommendingPostIDs(ids...)
	return _c
}

// AddRecommendingPosts adds the "recommending_posts" edges to the Post entity.
func (_c *PostCreate) AddRecommendingPosts(v ...*Post) *PostCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecommendingPostIDs(ids...)
}

// SetRecommendedPost sets the "recommended_post" edge to the Post entity.
func (_c *PostCreate) SetRecommendedPost(v *Post) *PostCreate {
	return _c.SetRecommendedPostID(v.ID)
}

// AddLikeIDs adds the "likes" edge to the Like entity by IDs.
func (_c *PostCreate) AddLikeIDs(ids ...int64) *PostCreate {
	_c.mutation.AddLikeIDs(ids...)
	return _c
}

// AddLikes adds the "likes" edges to the Like entity.
func (_c *PostCreate) AddLikes(v ...*Like) *PostCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLikeIDs(ids...)
}

// AddImageIDs adds the "images" edge to the Image entity by IDs.
func (_c *PostCreate) AddImageIDs(ids ...int64) *PostCreate {
	_c.mutation.AddImageIDs(ids...)
	return _c
}

// AddImages adds the "images" edges to the Image entity.
func (_c *PostCreate) AddImages(v ...*Image) *PostCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddImageIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := post.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.IsNsfw(); !ok {
		v := post.DefaultIsNsfw
		_c.mutation.SetIsNsfw(v)
	}
	if _, ok := _c.mutation.LikedCount(); !ok {
		v := post.DefaultLikedCount
		_c.mutation.SetLikedCount(v)
	}
	if _, ok := _c.mutation.RecommendedCount(); !ok {
		v := post.DefaultRecommendedCount
		_c.mutation.SetRecommendedCount(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := post.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Post.user_id"`)}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "Post.is_public"`)}
	}
	if _, ok := _c.mutation.IsNsfw(); !ok {
		return &ValidationError{Name: "is_nsfw", err: errors.New(`ent: missing required field "Post.is_nsfw"`)}
	}
	if _, ok := _c.mutation.LikedCount(); !ok {
		return &ValidationError{Name: "liked_count", err: errors.New(`ent: missing required field "Post.liked_count"`)}
	}
	if v, ok := _c.mutation.LikedCount(); ok {
		if err := post.LikedCountValidator(v); err != nil {
			return &ValidationError{Name: "liked_count", err: fmt.Errorf(`ent: validator failed for field "Post.liked_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecommendedCount(); !ok {
		return &ValidationError{Name: "recommended_count", err: errors.New(`ent: missing required field "Post.recommended_count"`)}
	}
	if v, ok := _c.mutation.RecommendedCount(); ok {
		if err := post.RecommendedCountValidator(v); err != nil {
			return &ValidationError{Name: "recommended_count", err: fmt.Errorf(`ent: validator failed for field "Post.recommended_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Post.view_count"`)}
	}
	if v, ok := _c.mutation.ViewCount(); ok {
		if err := post.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Post.view_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Post.user"`)}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Caption(); ok {
		_spec.SetField(post.FieldCaption, field.TypeString, value)
		_node.Caption = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(post.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.IsNsfw(); ok {
		_spec.SetField(post.FieldIsNsfw, field.TypeBool, value)
		_node.IsNsfw = value
	}
	if value, ok := _c.mutation.LikedCount(); ok {
		_spec.SetField(post.FieldLikedCount, field.TypeInt, value)
		_node.LikedCount = value
	}
	if value, ok := _c.mutation.RecommendedCount(); ok {
		_spec.SetField(post.FieldRecommendedCount, field.TypeInt, value)
		_node.RecommendedCount = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.UserTable,
			Columns: []string{post.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecommendingPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecommendedPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.RecommendedPostTable,
			Columns: []string{post.RecommendedPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecommendedPostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
