// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keu-5/muzee/backend/ent/image"
	"github.com/keu-5/muzee/backend/ent/like"
	"github.com/keu-5/muzee/backend/ent/post"
	"github.com/keu-5/muzee/backend/ent/predicate"
	"github.com/keu-5/muzee/backend/ent/user"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PostUpdate) SetUserID(v int64) *PostUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableUserID(v *int64) *PostUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRecommendedPostID sets the "recommended_post_id" field.
func (_u *PostUpdate) SetRecommendedPostID(v int64) *PostUpdate {
	_u.mutation.SetRecommendedPostID(v)
	return _u
}

// SetNillableRecommendedPostID sets the "recommended_post_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableRecommendedPostID(v *int64) *PostUpdate {
	if v != nil {
		_u.SetRecommendedPostID(*v)
	}
	return _u
}

// ClearRecommendedPostID clears the value of the "recommended_post_id" field.
func (_u *PostUpdate) ClearRecommendedPostID() *PostUpdate {
	_u.mutation.ClearRecommendedPostID()
	return _u
}

// SetCaption sets the "caption" field.
func (_u *PostUpdate) SetCaption(v string) *PostUpdate {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCaption(v *string) *PostUpdate {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *PostUpdate) ClearCaption() *PostUpdate {
	_u.mutation.ClearCaption()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PostUpdate) SetIsPublic(v bool) *PostUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PostUpdate) SetNillableIsPublic(v *bool) *PostUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetIsNsfw sets the "is_nsfw" field.
func (_u *PostUpdate) SetIsNsfw(v bool) *PostUpdate {
	_u.mutation.SetIsNsfw(v)
	return _u
}

// SetNillableIsNsfw sets the "is_nsfw" field if the given value is not nil.
func (_u *PostUpdate) SetNillableIsNsfw(v *bool) *PostUpdate {
	if v != nil {
		_u.SetIsNsfw(*v)
	}
	return _u
}

// SetLikedCount sets the "liked_count" field.
func (_u *PostUpdate) SetLikedCount(v int) *PostUpdate {
	_u.mutation.ResetLikedCount()
	_u.mutation.SetLikedCount(v)
	return _u
}

// SetNillableLikedCount sets the "liked_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLikedCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetLikedCount(*v)
	}
	return _u
}

// AddLikedCount adds value to the "liked_count" field.
func (_u *PostUpdate) AddLikedCount(v int) *PostUpdate {
	_u.mutation.AddLikedCount(v)
	return _u
}

// SetRecommendedCount sets the "recommended_count" field.
func (_u *PostUpdate) SetRecommendedCount(v int) *PostUpdate {
	_u.mutation.ResetRecommendedCount()
	_u.mutation.SetRecommendedCount(v)
	return _u
}

// SetNillableRecommendedCount sets the "recommended_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableRecommendedCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetRecommendedCount(*v)
	}
	return _u
}

// AddRecommendedCount adds value to the "recommended_count" field.
func (_u *PostUpdate) AddRecommendedCount(v int) *PostUpdate {
	_u.mutation.AddRecommendedCount(v)
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PostUpdate) SetViewCount(v int) *PostUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableViewCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PostUpdate) AddViewCount(v int) *PostUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PostUpdate) SetUser(v *User) *PostUpdate {
	return _u.SetUserID(v.ID)
}

// AddRecommendingPostIDs adds the "recommending_posts" edge to the Post entity by IDs.
func (_u *PostUpdate) AddRecommendingPostIDs(ids ...int64) *PostUpdate {
	_u.mutation.AddRecommendingPostIDs(ids...)
	return _u
}

// AddRecommendingPosts adds the "recommending_posts" edges to the Post entity.
func (_u *PostUpdate) AddRecommendingPosts(v ...*Post) *PostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecommendingPostIDs(ids...)
}

// SetRecommendedPost sets the "recommended_post" edge to the Post entity.
func (_u *PostUpdate) SetRecommendedPost(v *Post) *PostUpdate {
	return _u.SetRecommendedPostID(v.ID)
}

// AddLikeIDs adds the "likes" edge to the Like entity by IDs.
func (_u *PostUpdate) AddLikeIDs(ids ...int64) *PostUpdate {
	_u.mutation.AddLikeIDs(ids...)
	return _u
}

// AddLikes adds the "likes" edges to the Like entity.
func (_u *PostUpdate) AddLikes(v ...*Like) *PostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLikeIDs(ids...)
}

// AddImageIDs adds the "images" edge to the Image entity by IDs.
func (_u *PostUpdate) AddImageIDs(ids ...int64) *PostUpdate {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the Image entity.
func (_u *PostUpdate) AddImages(v ...*Image) *PostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PostUpdate) ClearUser() *PostUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRecommendingPosts clears all "recommending_posts" edges to the Post entity.
func (_u *PostUpdate) ClearRecommendingPosts() *PostUpdate {
	_u.mutation.ClearRecommendingPosts()
	return _u
}

// RemoveRecommendingPostIDs removes the "recommending_posts" edge to Post entities by IDs.
func (_u *PostUpdate) RemoveRecommendingPostIDs(ids ...int64) *PostUpdate {
	_u.mutation.RemoveRecommendingPostIDs(ids...)
	return _u
}

// RemoveRecommendingPosts removes "recommending_posts" edges to Post entities.
func (_u *PostUpdate) RemoveRecommendingPosts(v ...*Post) *PostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecommendingPostIDs(ids...)
}

// ClearRecommendedPost clears the "recommended_post" edge to the Post entity.
func (_u *PostUpdate) ClearRecommendedPost() *PostUpdate {
	_u.mutation.ClearRecommendedPost()
	return _u
}

// ClearLikes clears all "likes" edges to the Like entity.
func (_u *PostUpdate) ClearLikes() *PostUpdate {
	_u.mutation.ClearLikes()
	return _u
}

// RemoveLikeIDs removes the "likes" edge to Like entities by IDs.
func (_u *PostUpdate) RemoveLikeIDs(ids ...int64) *PostUpdate {
	_u.mutation.RemoveLikeIDs(ids...)
	return _u
}

// RemoveLikes removes "likes" edges to Like entities.
func (_u *PostUpdate) RemoveLikes(v ...*Like) *PostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLikeIDs(ids...)
}

// ClearImages clears all "images" edges to the Image entity.
func (_u *PostUpdate) ClearImages() *PostUpdate {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to Image entities by IDs.
func (_u *PostUpdate) RemoveImageIDs(ids ...int64) *PostUpdate {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to Image entities.
func (_u *PostUpdate) RemoveImages(v ...*Image) *PostUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.LikedCount(); ok {
		if err := post.LikedCountValidator(v); err != nil {
			return &ValidationError{Name: "liked_count", err: fmt.Errorf(`ent: validator failed for field "Post.liked_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecommendedCount(); ok {
		if err := post.RecommendedCountValidator(v); err != nil {
			return &ValidationError{Name: "recommended_count", err: fmt.Errorf(`ent: validator failed for field "Post.recommended_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := post.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Post.view_count": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.user"`)
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(post.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(post.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(post.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsNsfw(); ok {
		_spec.SetField(post.FieldIsNsfw, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LikedCount(); ok {
		_spec.SetField(post.FieldLikedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikedCount(); ok {
		_spec.AddField(post.FieldLikedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecommendedCount(); ok {
		_spec.SetField(post.FieldRecommendedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecommendedCount(); ok {
		_spec.AddField(post.FieldRecommendedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.UserTable,
			Columns: []string{post.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.UserTable,
			Columns: []string{post.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecommendingPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecommendingPostsIDs(); len(nodes) > 0 && !_u.mutation.RecommendingPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecommendingPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecommendedPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.RecommendedPostTable,
			Columns: []string{post.RecommendedPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecommendedPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.RecommendedPostTable,
			Columns: []string{post.RecommendedPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLikesIDs(); len(nodes) > 0 && !_u.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetUserID sets the "user_id" field.
func (_u *PostUpdateOne) SetUserID(v int64) *PostUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableUserID(v *int64) *PostUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRecommendedPostID sets the "recommended_post_id" field.
func (_u *PostUpdateOne) SetRecommendedPostID(v int64) *PostUpdateOne {
	_u.mutation.SetRecommendedPostID(v)
	return _u
}

// SetNillableRecommendedPostID sets the "recommended_post_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableRecommendedPostID(v *int64) *PostUpdateOne {
	if v != nil {
		_u.SetRecommendedPostID(*v)
	}
	return _u
}

// ClearRecommendedPostID clears the value of the "recommended_post_id" field.
func (_u *PostUpdateOne) ClearRecommendedPostID() *PostUpdateOne {
	_u.mutation.ClearRecommendedPostID()
	return _u
}

// SetCaption sets the "caption" field.
func (_u *PostUpdateOne) SetCaption(v string) *PostUpdateOne {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCaption(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *PostUpdateOne) ClearCaption() *PostUpdateOne {
	_u.mutation.ClearCaption()
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PostUpdateOne) SetIsPublic(v bool) *PostUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableIsPublic(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetIsNsfw sets the "is_nsfw" field.
func (_u *PostUpdateOne) SetIsNsfw(v bool) *PostUpdateOne {
	_u.mutation.SetIsNsfw(v)
	return _u
}

// SetNillableIsNsfw sets the "is_nsfw" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableIsNsfw(v *bool) *PostUpdateOne {
	if v != nil {
		_u.SetIsNsfw(*v)
	}
	return _u
}

// SetLikedCount sets the "liked_count" field.
func (_u *PostUpdateOne) SetLikedCount(v int) *PostUpdateOne {
	_u.mutation.ResetLikedCount()
	_u.mutation.SetLikedCount(v)
	return _u
}

// SetNillableLikedCount sets the "liked_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLikedCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetLikedCount(*v)
	}
	return _u
}

// AddLikedCount adds value to the "liked_count" field.
func (_u *PostUpdateOne) AddLikedCount(v int) *PostUpdateOne {
	_u.mutation.AddLikedCount(v)
	return _u
}

// SetRecommendedCount sets the "recommended_count" field.
func (_u *PostUpdateOne) SetRecommendedCount(v int) *PostUpdateOne {
	_u.mutation.ResetRecommendedCount()
	_u.mutation.SetRecommendedCount(v)
	return _u
}

// SetNillableRecommendedCount sets the "recommended_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableRecommendedCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetRecommendedCount(*v)
	}
	return _u
}

// AddRecommendedCount adds value to the "recommended_count" field.
func (_u *PostUpdateOne) AddRecommendedCount(v int) *PostUpdateOne {
	_u.mutation.AddRecommendedCount(v)
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PostUpdateOne) SetViewCount(v int) *PostUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableViewCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PostUpdateOne) AddViewCount(v int) *PostUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PostUpdateOne) SetUser(v *User) *PostUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddRecommendingPostIDs adds the "recommending_posts" edge to the Post entity by IDs.
func (_u *PostUpdateOne) AddRecommendingPostIDs(ids ...int64) *PostUpdateOne {
	_u.mutation.AddRecommendingPostIDs(ids...)
	return _u
}

// AddRecommendingPosts adds the "recommending_posts" edges to the Post entity.
func (_u *PostUpdateOne) AddRecommendingPosts(v ...*Post) *PostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRecommendingPostIDs(ids...)
}

// SetRecommendedPost sets the "recommended_post" edge to the Post entity.
func (_u *PostUpdateOne) SetRecommendedPost(v *Post) *PostUpdateOne {
	return _u.SetRecommendedPostID(v.ID)
}

// AddLikeIDs adds the "likes" edge to the Like entity by IDs.
func (_u *PostUpdateOne) AddLikeIDs(ids ...int64) *PostUpdateOne {
	_u.mutation.AddLikeIDs(ids...)
	return _u
}

// AddLikes adds the "likes" edges to the Like entity.
func (_u *PostUpdateOne) AddLikes(v ...*Like) *PostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLikeIDs(ids...)
}

// AddImageIDs adds the "images" edge to the Image entity by IDs.
func (_u *PostUpdateOne) AddImageIDs(ids ...int64) *PostUpdateOne {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the Image entity.
func (_u *PostUpdateOne) AddImages(v ...*Image) *PostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PostUpdateOne) ClearUser() *PostUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRecommendingPosts clears all "recommending_posts" edges to the Post entity.
func (_u *PostUpdateOne) ClearRecommendingPosts() *PostUpdateOne {
	_u.mutation.ClearRecommendingPosts()
	return _u
}

// RemoveRecommendingPostIDs removes the "recommending_posts" edge to Post entities by IDs.
func (_u *PostUpdateOne) RemoveRecommendingPostIDs(ids ...int64) *PostUpdateOne {
	_u.mutation.RemoveRecommendingPostIDs(ids...)
	return _u
}

// RemoveRecommendingPosts removes "recommending_posts" edges to Post entities.
func (_u *PostUpdateOne) RemoveRecommendingPosts(v ...*Post) *PostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRecommendingPostIDs(ids...)
}

// ClearRecommendedPost clears the "recommended_post" edge to the Post entity.
func (_u *PostUpdateOne) ClearRecommendedPost() *PostUpdateOne {
	_u.mutation.ClearRecommendedPost()
	return _u
}

// ClearLikes clears all "likes" edges to the Like entity.
func (_u *PostUpdateOne) ClearLikes() *PostUpdateOne {
	_u.mutation.ClearLikes()
	return _u
}

// RemoveLikeIDs removes the "likes" edge to Like entities by IDs.
func (_u *PostUpdateOne) RemoveLikeIDs(ids ...int64) *PostUpdateOne {
	_u.mutation.RemoveLikeIDs(ids...)
	return _u
}

// RemoveLikes removes "likes" edges to Like entities.
func (_u *PostUpdateOne) RemoveLikes(v ...*Like) *PostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLikeIDs(ids...)
}

// ClearImages clears all "images" edges to the Image entity.
func (_u *PostUpdateOne) ClearImages() *PostUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to Image entities by IDs.
func (_u *PostUpdateOne) RemoveImageIDs(ids ...int64) *PostUpdateOne {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to Image entities.
func (_u *PostUpdateOne) RemoveImages(v ...*Image) *PostUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.LikedCount(); ok {
		if err := post.LikedCountValidator(v); err != nil {
			return &ValidationError{Name: "liked_count", err: fmt.Errorf(`ent: validator failed for field "Post.liked_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecommendedCount(); ok {
		if err := post.RecommendedCountValidator(v); err != nil {
			return &ValidationError{Name: "recommended_count", err: fmt.Errorf(`ent: validator failed for field "Post.recommended_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewCount(); ok {
		if err := post.ViewCountValidator(v); err != nil {
			return &ValidationError{Name: "view_count", err: fmt.Errorf(`ent: validator failed for field "Post.view_count": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Post.user"`)
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(post.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(post.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(post.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsNsfw(); ok {
		_spec.SetField(post.FieldIsNsfw, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LikedCount(); ok {
		_spec.SetField(post.FieldLikedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikedCount(); ok {
		_spec.AddField(post.FieldLikedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RecommendedCount(); ok {
		_spec.SetField(post.FieldRecommendedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecommendedCount(); ok {
		_spec.AddField(post.FieldRecommendedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.UserTable,
			Columns: []string{post.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.UserTable,
			Columns: []string{post.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecommendingPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRecommendingPostsIDs(); len(nodes) > 0 && !_u.mutation.RecommendingPostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecommendingPostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   post.RecommendingPostsTable,
			Columns: []string{post.RecommendingPostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecommendedPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.RecommendedPostTable,
			Columns: []string{post.RecommendedPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecommendedPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   post.RecommendedPostTable,
			Columns: []string{post.RecommendedPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLikesIDs(); len(nodes) > 0 && !_u.mutation.LikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.LikesTable,
			Columns: []string{post.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   post.ImagesTable,
			Columns: []string{post.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
