// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/keu-5/muzee/backend/ent/post"
	"github.com/keu-5/muzee/backend/ent/user"
)

// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RecommendedPostID holds the value of the "recommended_post_id" field.
	RecommendedPostID int64 `json:"recommended_post_id,omitempty"`
	// Caption holds the value of the "caption" field.
	Caption string `json:"caption,omitempty"`
	// IsPublic holds the value of the "is_public" field.
	IsPublic bool `json:"is_public,omitempty"`
	// IsNsfw holds the value of the "is_nsfw" field.
	IsNsfw bool `json:"is_nsfw,omitempty"`
	// LikedCount holds the value of the "liked_count" field.
	LikedCount int `json:"liked_count,omitempty"`
	// RecommendedCount holds the value of the "recommended_count" field.
	RecommendedCount int `json:"recommended_count,omitempty"`
	// ViewCount holds the value of the "view_count" field.
	ViewCount int `json:"view_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges        PostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// RecommendingPosts holds the value of the recommending_posts edge.
	RecommendingPosts []*Post `json:"recommended_post,omitempty"`
	// RecommendedPost holds the value of the recommended_post edge.
	RecommendedPost *Post `json:"recommended_post,omitempty"`
	// Likes holds the value of the likes edge.
	Likes []*Like `json:"likes,omitempty"`
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RecommendingPostsOrErr returns the RecommendingPosts value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) RecommendingPostsOrErr() ([]*Post, error) {
	if e.loadedTypes[1] {
		return e.RecommendingPosts, nil
	}
	return nil, &NotLoadedError{edge: "recommending_posts"}
}

// RecommendedPostOrErr returns the RecommendedPost value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostEdges) RecommendedPostOrErr() (*Post, error) {
	if e.RecommendedPost != nil {
		return e.RecommendedPost, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "recommended_post"}
}

// LikesOrErr returns the Likes value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) LikesOrErr() ([]*Like, error) {
	if e.loadedTypes[3] {
		return e.Likes, nil
	}
	return nil, &NotLoadedError{edge: "likes"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e PostEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[4] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Post) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case post.FieldIsPublic, post.FieldIsNsfw:
			values[i] = new(sql.NullBool)
		case post.FieldID, post.FieldUserID, post.FieldRecommendedPostID, post.FieldLikedCount, post.FieldRecommendedCount, post.FieldViewCount:
			values[i] = new(sql.NullInt64)
		case post.FieldCaption:
			values[i] = new(sql.NullString)
		case post.FieldCreatedAt, post.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Post fields.
func (_m *Post) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case post.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case post.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case post.FieldRecommendedPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recommended_post_id", values[i])
			} else if value.Valid {
				_m.RecommendedPostID = value.Int64
			}
		case post.FieldCaption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caption", values[i])
			} else if value.Valid {
				_m.Caption = value.String
			}
		case post.FieldIsPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_public", values[i])
			} else if value.Valid {
				_m.IsPublic = value.Bool
			}
		case post.FieldIsNsfw:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_nsfw", values[i])
			} else if value.Valid {
				_m.IsNsfw = value.Bool
			}
		case post.FieldLikedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field liked_count", values[i])
			} else if value.Valid {
				_m.LikedCount = int(value.Int64)
			}
		case post.FieldRecommendedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recommended_count", values[i])
			} else if value.Valid {
				_m.RecommendedCount = int(value.Int64)
			}
		case post.FieldViewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field view_count", values[i])
			} else if value.Valid {
				_m.ViewCount = int(value.Int64)
			}
		case post.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case post.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Post.
// This includes values selected through modifiers, order, etc.
func (_m *Post) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Post entity.
func (_m *Post) QueryUser() *UserQuery {
	return NewPostClient(_m.config).QueryUser(_m)
}

// QueryRecommendingPosts queries the "recommending_posts" edge of the Post entity.
func (_m *Post) QueryRecommendingPosts() *PostQuery {
	return NewPostClient(_m.config).QueryRecommendingPosts(_m)
}

// QueryRecommendedPost queries the "recommended_post" edge of the Post entity.
func (_m *Post) QueryRecommendedPost() *PostQuery {
	return NewPostClient(_m.config).QueryRecommendedPost(_m)
}

// QueryLikes queries the "likes" edge of the Post entity.
func (_m *Post) QueryLikes() *LikeQuery {
	return NewPostClient(_m.config).QueryLikes(_m)
}

// QueryImages queries the "images" edge of the Post entity.
func (_m *Post) QueryImages() *ImageQuery {
	return NewPostClient(_m.config).QueryImages(_m)
}

// Update returns a builder for updating this Post.
// Note that you need to call Post.Unwrap() before calling this method if this Post
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Post) Update() *PostUpdateOne {
	return NewPostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Post entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Post) Unwrap() *Post {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Post is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Post) String() string {
	var builder strings.Builder
	builder.WriteString("Post(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("recommended_post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecommendedPostID))
	builder.WriteString(", ")
	builder.WriteString("caption=")
	builder.WriteString(_m.Caption)
	builder.WriteString(", ")
	builder.WriteString("is_public=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublic))
	builder.WriteString(", ")
	builder.WriteString("is_nsfw=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsNsfw))
	builder.WriteString(", ")
	builder.WriteString("liked_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.LikedCount))
	builder.WriteString(", ")
	builder.WriteString("recommended_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecommendedCount))
	builder.WriteString(", ")
	builder.WriteString("view_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Posts is a parsable slice of Post.
type Posts []*Post
