// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/keu-5/muzee/backend/ent/schema"
	"github.com/keu-5/muzee/backend/ent/user"
	"github.com/keu-5/muzee/backend/ent/userprofile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userprofileFields := schema.UserProfile{}.Fields()
	_ = userprofileFields
	// userprofileDescName is the schema descriptor for name field.
	userprofileDescName := userprofileFields[1].Descriptor()
	// userprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userprofile.NameValidator = func() func(string) error {
		validators := userprofileDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userprofileDescUsername is the schema descriptor for username field.
	userprofileDescUsername := userprofileFields[2].Descriptor()
	// userprofile.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	userprofile.UsernameValidator = func() func(string) error {
		validators := userprofileDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userprofileDescIconPath is the schema descriptor for icon_path field.
	userprofileDescIconPath := userprofileFields[3].Descriptor()
	// userprofile.IconPathValidator is a validator for the "icon_path" field. It is called by the builders before save.
	userprofile.IconPathValidator = userprofileDescIconPath.Validators[0].(func(string) error)
	// userprofileDescCreatedAt is the schema descriptor for created_at field.
	userprofileDescCreatedAt := userprofileFields[4].Descriptor()
	// userprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	userprofile.DefaultCreatedAt = userprofileDescCreatedAt.Default.(func() time.Time)
	// userprofileDescUpdatedAt is the schema descriptor for updated_at field.
	userprofileDescUpdatedAt := userprofileFields[5].Descriptor()
	// userprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userprofile.DefaultUpdatedAt = userprofileDescUpdatedAt.Default.(func() time.Time)
	// userprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userprofile.UpdateDefaultUpdatedAt = userprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
}
