// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/keu-5/muzee/backend/ent/like"
	"github.com/keu-5/muzee/backend/ent/post"
	"github.com/keu-5/muzee/backend/ent/schema"
	"github.com/keu-5/muzee/backend/ent/user"
	"github.com/keu-5/muzee/backend/ent/userprofile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	likeFields := schema.Like{}.Fields()
	_ = likeFields
	// likeDescCreatedAt is the schema descriptor for created_at field.
	likeDescCreatedAt := likeFields[3].Descriptor()
	// like.DefaultCreatedAt holds the default value on creation for the created_at field.
	like.DefaultCreatedAt = likeDescCreatedAt.Default.(func() time.Time)
	// likeDescUpdatedAt is the schema descriptor for updated_at field.
	likeDescUpdatedAt := likeFields[4].Descriptor()
	// like.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	like.DefaultUpdatedAt = likeDescUpdatedAt.Default.(func() time.Time)
	// like.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	like.UpdateDefaultUpdatedAt = likeDescUpdatedAt.UpdateDefault.(func() time.Time)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescIsPublic is the schema descriptor for is_public field.
	postDescIsPublic := postFields[4].Descriptor()
	// post.DefaultIsPublic holds the default value on creation for the is_public field.
	post.DefaultIsPublic = postDescIsPublic.Default.(bool)
	// postDescIsNsfw is the schema descriptor for is_nsfw field.
	postDescIsNsfw := postFields[5].Descriptor()
	// post.DefaultIsNsfw holds the default value on creation for the is_nsfw field.
	post.DefaultIsNsfw = postDescIsNsfw.Default.(bool)
	// postDescLikedCount is the schema descriptor for liked_count field.
	postDescLikedCount := postFields[6].Descriptor()
	// post.DefaultLikedCount holds the default value on creation for the liked_count field.
	post.DefaultLikedCount = postDescLikedCount.Default.(int)
	// post.LikedCountValidator is a validator for the "liked_count" field. It is called by the builders before save.
	post.LikedCountValidator = postDescLikedCount.Validators[0].(func(int) error)
	// postDescRecommendedCount is the schema descriptor for recommended_count field.
	postDescRecommendedCount := postFields[7].Descriptor()
	// post.DefaultRecommendedCount holds the default value on creation for the recommended_count field.
	post.DefaultRecommendedCount = postDescRecommendedCount.Default.(int)
	// post.RecommendedCountValidator is a validator for the "recommended_count" field. It is called by the builders before save.
	post.RecommendedCountValidator = postDescRecommendedCount.Validators[0].(func(int) error)
	// postDescViewCount is the schema descriptor for view_count field.
	postDescViewCount := postFields[8].Descriptor()
	// post.DefaultViewCount holds the default value on creation for the view_count field.
	post.DefaultViewCount = postDescViewCount.Default.(int)
	// post.ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	post.ViewCountValidator = postDescViewCount.Validators[0].(func(int) error)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[9].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[10].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password_hash string) error {
			for _, fn := range fns {
				if err := fn(password_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	userprofileFields := schema.UserProfile{}.Fields()
	_ = userprofileFields
	// userprofileDescName is the schema descriptor for name field.
	userprofileDescName := userprofileFields[2].Descriptor()
	// userprofile.NameValidator is a validator for the "name" field. It is called by the builders before save.
	userprofile.NameValidator = func() func(string) error {
		validators := userprofileDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userprofileDescUsername is the schema descriptor for username field.
	userprofileDescUsername := userprofileFields[3].Descriptor()
	// userprofile.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	userprofile.UsernameValidator = func() func(string) error {
		validators := userprofileDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userprofileDescIconPath is the schema descriptor for icon_path field.
	userprofileDescIconPath := userprofileFields[4].Descriptor()
	// userprofile.IconPathValidator is a validator for the "icon_path" field. It is called by the builders before save.
	userprofile.IconPathValidator = userprofileDescIconPath.Validators[0].(func(string) error)
	// userprofileDescCreatedAt is the schema descriptor for created_at field.
	userprofileDescCreatedAt := userprofileFields[5].Descriptor()
	// userprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	userprofile.DefaultCreatedAt = userprofileDescCreatedAt.Default.(func() time.Time)
	// userprofileDescUpdatedAt is the schema descriptor for updated_at field.
	userprofileDescUpdatedAt := userprofileFields[6].Descriptor()
	// userprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userprofile.DefaultUpdatedAt = userprofileDescUpdatedAt.Default.(func() time.Time)
	// userprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userprofile.UpdateDefaultUpdatedAt = userprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
}
