// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keu-5/muzee/backend/ent/predicate"
	"github.com/keu-5/muzee/backend/ent/user"
	"github.com/keu-5/muzee/backend/ent/userprofile"
)

// UserProfileUpdate is the builder for updating UserProfile entities.
type UserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserProfileMutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdate) Where(ps ...predicate.UserProfile) *UserProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *UserProfileUpdate) SetName(v string) *UserProfileUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableName(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserProfileUpdate) SetUsername(v string) *UserProfileUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableUsername(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIconPath sets the "icon_path" field.
func (_u *UserProfileUpdate) SetIconPath(v string) *UserProfileUpdate {
	_u.mutation.SetIconPath(v)
	return _u
}

// SetNillableIconPath sets the "icon_path" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableIconPath(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetIconPath(*v)
	}
	return _u
}

// ClearIconPath clears the value of the "icon_path" field.
func (_u *UserProfileUpdate) ClearIconPath() *UserProfileUpdate {
	_u.mutation.ClearIconPath()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserProfileUpdate) SetUpdatedAt(v time.Time) *UserProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserProfileUpdate) SetUserID(id int64) *UserProfileUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserProfileUpdate) SetUser(v *User) *UserProfileUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdate) Mutation() *UserProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserProfileUpdate) ClearUser() *UserProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := userprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserProfile.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := userprofile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserProfile.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconPath(); ok {
		if err := userprofile.IconPathValidator(v); err != nil {
			return &ValidationError{Name: "icon_path", err: fmt.Errorf(`ent: validator failed for field "UserProfile.icon_path": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserProfile.user"`)
	}
	return nil
}

func (_u *UserProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(userprofile.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconPath(); ok {
		_spec.SetField(userprofile.FieldIconPath, field.TypeString, value)
	}
	if _u.mutation.IconPathCleared() {
		_spec.ClearField(userprofile.FieldIconPath, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserProfileUpdateOne is the builder for updating a single UserProfile entity.
type UserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserProfileMutation
}

// SetName sets the "name" field.
func (_u *UserProfileUpdateOne) SetName(v string) *UserProfileUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableName(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserProfileUpdateOne) SetUsername(v string) *UserProfileUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableUsername(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetIconPath sets the "icon_path" field.
func (_u *UserProfileUpdateOne) SetIconPath(v string) *UserProfileUpdateOne {
	_u.mutation.SetIconPath(v)
	return _u
}

// SetNillableIconPath sets the "icon_path" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableIconPath(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetIconPath(*v)
	}
	return _u
}

// ClearIconPath clears the value of the "icon_path" field.
func (_u *UserProfileUpdateOne) ClearIconPath() *UserProfileUpdateOne {
	_u.mutation.ClearIconPath()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserProfileUpdateOne) SetUpdatedAt(v time.Time) *UserProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserProfileUpdateOne) SetUserID(id int64) *UserProfileUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserProfileUpdateOne) SetUser(v *User) *UserProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdateOne) Mutation() *UserProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserProfileUpdateOne) ClearUser() *UserProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdateOne) Where(ps ...predicate.UserProfile) *UserProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserProfileUpdateOne) Select(field string, fields ...string) *UserProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserProfile entity.
func (_u *UserProfileUpdateOne) Save(ctx context.Context) (*UserProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdateOne) SaveX(ctx context.Context) *UserProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := userprofile.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserProfile.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := userprofile.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserProfile.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconPath(); ok {
		if err := userprofile.IconPathValidator(v); err != nil {
			return &ValidationError{Name: "icon_path", err: fmt.Errorf(`ent: validator failed for field "UserProfile.icon_path": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserProfile.user"`)
	}
	return nil
}

func (_u *UserProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userprofile.Table, userprofile.Columns, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userprofile.FieldID)
		for _, f := range fields {
			if !userprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userprofile.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(userprofile.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconPath(); ok {
		_spec.SetField(userprofile.FieldIconPath, field.TypeString, value)
	}
	if _u.mutation.IconPathCleared() {
		_spec.ClearField(userprofile.FieldIconPath, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userprofile.UserTable,
			Columns: []string{userprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
