// Code generated by ent, DO NOT EDIT.

package post

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the post type in the database.
	Label = "post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRecommendedPostID holds the string denoting the recommended_post_id field in the database.
	FieldRecommendedPostID = "recommended_post_id"
	// FieldCaption holds the string denoting the caption field in the database.
	FieldCaption = "caption"
	// FieldIsPublic holds the string denoting the is_public field in the database.
	FieldIsPublic = "is_public"
	// FieldIsNsfw holds the string denoting the is_nsfw field in the database.
	FieldIsNsfw = "is_nsfw"
	// FieldLikedCount holds the string denoting the liked_count field in the database.
	FieldLikedCount = "liked_count"
	// FieldRecommendedCount holds the string denoting the recommended_count field in the database.
	FieldRecommendedCount = "recommended_count"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRecommendingPosts holds the string denoting the recommending_posts edge name in mutations.
	EdgeRecommendingPosts = "recommending_posts"
	// EdgeRecommendedPost holds the string denoting the recommended_post edge name in mutations.
	EdgeRecommendedPost = "recommended_post"
	// EdgeLikes holds the string denoting the likes edge name in mutations.
	EdgeLikes = "likes"
	// EdgeImages holds the string denoting the images edge name in mutations.
	EdgeImages = "images"
	// Table holds the table name of the post in the database.
	Table = "posts"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "posts"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// RecommendingPostsTable is the table that holds the recommending_posts relation/edge.
	RecommendingPostsTable = "posts"
	// RecommendingPostsColumn is the table column denoting the recommending_posts relation/edge.
	RecommendingPostsColumn = "recommended_post_id"
	// RecommendedPostTable is the table that holds the recommended_post relation/edge.
	RecommendedPostTable = "posts"
	// RecommendedPostColumn is the table column denoting the recommended_post relation/edge.
	RecommendedPostColumn = "recommended_post_id"
	// LikesTable is the table that holds the likes relation/edge.
	LikesTable = "likes"
	// LikesInverseTable is the table name for the Like entity.
	// It exists in this package in order to avoid circular dependency with the "like" package.
	LikesInverseTable = "likes"
	// LikesColumn is the table column denoting the likes relation/edge.
	LikesColumn = "post_id"
	// ImagesTable is the table that holds the images relation/edge.
	ImagesTable = "images"
	// ImagesInverseTable is the table name for the Image entity.
	// It exists in this package in order to avoid circular dependency with the "image" package.
	ImagesInverseTable = "images"
	// ImagesColumn is the table column denoting the images relation/edge.
	ImagesColumn = "post_id"
)

// Columns holds all SQL columns for post fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldRecommendedPostID,
	FieldCaption,
	FieldIsPublic,
	FieldIsNsfw,
	FieldLikedCount,
	FieldRecommendedCount,
	FieldViewCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsPublic holds the default value on creation for the "is_public" field.
	DefaultIsPublic bool
	// DefaultIsNsfw holds the default value on creation for the "is_nsfw" field.
	DefaultIsNsfw bool
	// DefaultLikedCount holds the default value on creation for the "liked_count" field.
	DefaultLikedCount int
	// LikedCountValidator is a validator for the "liked_count" field. It is called by the builders before save.
	LikedCountValidator func(int) error
	// DefaultRecommendedCount holds the default value on creation for the "recommended_count" field.
	DefaultRecommendedCount int
	// RecommendedCountValidator is a validator for the "recommended_count" field. It is called by the builders before save.
	RecommendedCountValidator func(int) error
	// DefaultViewCount holds the default value on creation for the "view_count" field.
	DefaultViewCount int
	// ViewCountValidator is a validator for the "view_count" field. It is called by the builders before save.
	ViewCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Post queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRecommendedPostID orders the results by the recommended_post_id field.
func ByRecommendedPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecommendedPostID, opts...).ToFunc()
}

// ByCaption orders the results by the caption field.
func ByCaption(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCaption, opts...).ToFunc()
}

// ByIsPublic orders the results by the is_public field.
func ByIsPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublic, opts...).ToFunc()
}

// ByIsNsfw orders the results by the is_nsfw field.
func ByIsNsfw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsNsfw, opts...).ToFunc()
}

// ByLikedCount orders the results by the liked_count field.
func ByLikedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikedCount, opts...).ToFunc()
}

// ByRecommendedCount orders the results by the recommended_count field.
func ByRecommendedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecommendedCount, opts...).ToFunc()
}

// ByViewCount orders the results by the view_count field.
func ByViewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByRecommendingPostsCount orders the results by recommending_posts count.
func ByRecommendingPostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecommendingPostsStep(), opts...)
	}
}

// ByRecommendingPosts orders the results by recommending_posts terms.
func ByRecommendingPosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecommendingPostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecommendedPostField orders the results by recommended_post field.
func ByRecommendedPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecommendedPostStep(), sql.OrderByField(field, opts...))
	}
}

// ByLikesCount orders the results by likes count.
func ByLikesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLikesStep(), opts...)
	}
}

// ByLikes orders the results by likes terms.
func ByLikes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLikesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByImagesCount orders the results by images count.
func ByImagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImagesStep(), opts...)
	}
}

// ByImages orders the results by images terms.
func ByImages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newRecommendingPostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RecommendingPostsTable, RecommendingPostsColumn),
	)
}
func newRecommendedPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RecommendedPostTable, RecommendedPostColumn),
	)
}
func newLikesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LikesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LikesTable, LikesColumn),
	)
}
func newImagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImagesTable, ImagesColumn),
	)
}
