// Code generated by ent, DO NOT EDIT.

package post

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/keu-5/muzee/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUserID, v))
}

// RecommendedPostID applies equality check predicate on the "recommended_post_id" field. It's identical to RecommendedPostIDEQ.
func RecommendedPostID(v int64) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldRecommendedPostID, v))
}

// Caption applies equality check predicate on the "caption" field. It's identical to CaptionEQ.
func Caption(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCaption, v))
}

// IsPublic applies equality check predicate on the "is_public" field. It's identical to IsPublicEQ.
func IsPublic(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldIsPublic, v))
}

// IsNsfw applies equality check predicate on the "is_nsfw" field. It's identical to IsNsfwEQ.
func IsNsfw(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldIsNsfw, v))
}

// LikedCount applies equality check predicate on the "liked_count" field. It's identical to LikedCountEQ.
func LikedCount(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldLikedCount, v))
}

// RecommendedCount applies equality check predicate on the "recommended_count" field. It's identical to RecommendedCountEQ.
func RecommendedCount(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldRecommendedCount, v))
}

// ViewCount applies equality check predicate on the "view_count" field. It's identical to ViewCountEQ.
func ViewCount(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldViewCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUserID, vs...))
}

// RecommendedPostIDEQ applies the EQ predicate on the "recommended_post_id" field.
func RecommendedPostIDEQ(v int64) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldRecommendedPostID, v))
}

// RecommendedPostIDNEQ applies the NEQ predicate on the "recommended_post_id" field.
func RecommendedPostIDNEQ(v int64) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldRecommendedPostID, v))
}

// RecommendedPostIDIn applies the In predicate on the "recommended_post_id" field.
func RecommendedPostIDIn(vs ...int64) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldRecommendedPostID, vs...))
}

// RecommendedPostIDNotIn applies the NotIn predicate on the "recommended_post_id" field.
func RecommendedPostIDNotIn(vs ...int64) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldRecommendedPostID, vs...))
}

// RecommendedPostIDIsNil applies the IsNil predicate on the "recommended_post_id" field.
func RecommendedPostIDIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldRecommendedPostID))
}

// RecommendedPostIDNotNil applies the NotNil predicate on the "recommended_post_id" field.
func RecommendedPostIDNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldRecommendedPostID))
}

// CaptionEQ applies the EQ predicate on the "caption" field.
func CaptionEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCaption, v))
}

// CaptionNEQ applies the NEQ predicate on the "caption" field.
func CaptionNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCaption, v))
}

// CaptionIn applies the In predicate on the "caption" field.
func CaptionIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCaption, vs...))
}

// CaptionNotIn applies the NotIn predicate on the "caption" field.
func CaptionNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCaption, vs...))
}

// CaptionGT applies the GT predicate on the "caption" field.
func CaptionGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCaption, v))
}

// CaptionGTE applies the GTE predicate on the "caption" field.
func CaptionGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCaption, v))
}

// CaptionLT applies the LT predicate on the "caption" field.
func CaptionLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCaption, v))
}

// CaptionLTE applies the LTE predicate on the "caption" field.
func CaptionLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCaption, v))
}

// CaptionContains applies the Contains predicate on the "caption" field.
func CaptionContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldCaption, v))
}

// CaptionHasPrefix applies the HasPrefix predicate on the "caption" field.
func CaptionHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldCaption, v))
}

// CaptionHasSuffix applies the HasSuffix predicate on the "caption" field.
func CaptionHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldCaption, v))
}

// CaptionIsNil applies the IsNil predicate on the "caption" field.
func CaptionIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldCaption))
}

// CaptionNotNil applies the NotNil predicate on the "caption" field.
func CaptionNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldCaption))
}

// CaptionEqualFold applies the EqualFold predicate on the "caption" field.
func CaptionEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldCaption, v))
}

// CaptionContainsFold applies the ContainsFold predicate on the "caption" field.
func CaptionContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldCaption, v))
}

// IsPublicEQ applies the EQ predicate on the "is_public" field.
func IsPublicEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldIsPublic, v))
}

// IsPublicNEQ applies the NEQ predicate on the "is_public" field.
func IsPublicNEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldIsPublic, v))
}

// IsNsfwEQ applies the EQ predicate on the "is_nsfw" field.
func IsNsfwEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldIsNsfw, v))
}

// IsNsfwNEQ applies the NEQ predicate on the "is_nsfw" field.
func IsNsfwNEQ(v bool) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldIsNsfw, v))
}

// LikedCountEQ applies the EQ predicate on the "liked_count" field.
func LikedCountEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldLikedCount, v))
}

// LikedCountNEQ applies the NEQ predicate on the "liked_count" field.
func LikedCountNEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldLikedCount, v))
}

// LikedCountIn applies the In predicate on the "liked_count" field.
func LikedCountIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldLikedCount, vs...))
}

// LikedCountNotIn applies the NotIn predicate on the "liked_count" field.
func LikedCountNotIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldLikedCount, vs...))
}

// LikedCountGT applies the GT predicate on the "liked_count" field.
func LikedCountGT(v int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldLikedCount, v))
}

// LikedCountGTE applies the GTE predicate on the "liked_count" field.
func LikedCountGTE(v int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldLikedCount, v))
}

// LikedCountLT applies the LT predicate on the "liked_count" field.
func LikedCountLT(v int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldLikedCount, v))
}

// LikedCountLTE applies the LTE predicate on the "liked_count" field.
func LikedCountLTE(v int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldLikedCount, v))
}

// RecommendedCountEQ applies the EQ predicate on the "recommended_count" field.
func RecommendedCountEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldRecommendedCount, v))
}

// RecommendedCountNEQ applies the NEQ predicate on the "recommended_count" field.
func RecommendedCountNEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldRecommendedCount, v))
}

// RecommendedCountIn applies the In predicate on the "recommended_count" field.
func RecommendedCountIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldRecommendedCount, vs...))
}

// RecommendedCountNotIn applies the NotIn predicate on the "recommended_count" field.
func RecommendedCountNotIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldRecommendedCount, vs...))
}

// RecommendedCountGT applies the GT predicate on the "recommended_count" field.
func RecommendedCountGT(v int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldRecommendedCount, v))
}

// RecommendedCountGTE applies the GTE predicate on the "recommended_count" field.
func RecommendedCountGTE(v int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldRecommendedCount, v))
}

// RecommendedCountLT applies the LT predicate on the "recommended_count" field.
func RecommendedCountLT(v int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldRecommendedCount, v))
}

// RecommendedCountLTE applies the LTE predicate on the "recommended_count" field.
func RecommendedCountLTE(v int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldRecommendedCount, v))
}

// ViewCountEQ applies the EQ predicate on the "view_count" field.
func ViewCountEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldViewCount, v))
}

// ViewCountNEQ applies the NEQ predicate on the "view_count" field.
func ViewCountNEQ(v int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldViewCount, v))
}

// ViewCountIn applies the In predicate on the "view_count" field.
func ViewCountIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldViewCount, vs...))
}

// ViewCountNotIn applies the NotIn predicate on the "view_count" field.
func ViewCountNotIn(vs ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldViewCount, vs...))
}

// ViewCountGT applies the GT predicate on the "view_count" field.
func ViewCountGT(v int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldViewCount, v))
}

// ViewCountGTE applies the GTE predicate on the "view_count" field.
func ViewCountGTE(v int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldViewCount, v))
}

// ViewCountLT applies the LT predicate on the "view_count" field.
func ViewCountLT(v int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldViewCount, v))
}

// ViewCountLTE applies the LTE predicate on the "view_count" field.
func ViewCountLTE(v int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldViewCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecommendingPosts applies the HasEdge predicate on the "recommending_posts" edge.
func HasRecommendingPosts() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RecommendingPostsTable, RecommendingPostsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecommendingPostsWith applies the HasEdge predicate on the "recommending_posts" edge with a given conditions (other predicates).
func HasRecommendingPostsWith(preds ...predicate.Post) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newRecommendingPostsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecommendedPost applies the HasEdge predicate on the "recommended_post" edge.
func HasRecommendedPost() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RecommendedPostTable, RecommendedPostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecommendedPostWith applies the HasEdge predicate on the "recommended_post" edge with a given conditions (other predicates).
func HasRecommendedPostWith(preds ...predicate.Post) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newRecommendedPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLikes applies the HasEdge predicate on the "likes" edge.
func HasLikes() predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LikesTable, LikesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLikesWith applies the HasEdge predicate on the "likes" edge with a given conditions (other predicates).
func HasLikesWith(preds ...predicate.Like) predicate.Post {
	return predicate.Post(func(s *sql.Selector) {
		step := newLikesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Post) predicate.Post {
	return predicate.Post(sql.NotPredicates(p))
}
