/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface _V1MeProfilePostRequest {
  /** User name (1-100 characters) */
  name: string;
  /** Username (1-50 characters) */
  username: string;
  /** Profile icon image (max 5MB, JPEG/PNG/GIF/WebP) */
  icon?: Blob;
}
