/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export type GetV1UserProfilesCheckUsernameParams = {
/**
 * Username to check (1–50 characters)
 */
username: string;
};
