/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import type { GithubComKeu5MuzeeBackendInternalHelperErrorResponseDetailsItem } from './githubComKeu5MuzeeBackendInternalHelperErrorResponseDetailsItem';

export interface GithubComKeu5MuzeeBackendInternalHelperErrorResponse {
  details?: GithubComKeu5MuzeeBackendInternalHelperErrorResponseDetailsItem[];
  error?: string;
  message?: string;
}
