/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface InternalInterfaceHandlerVerifyCodeRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  client_id: string;
  code: string;
  /** @maxLength 255 */
  email: string;
}
