/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface InternalInterfaceHandlerUserProfileResponse {
  created_at?: string;
  icon_path?: string;
  id?: number;
  name?: string;
  updated_at?: string;
  username?: string;
}
