/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface InternalInterfaceHandlerSendCodeRequest {
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 8
   * @maxLength 72
   */
  password: string;
}
