/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface InternalInterfaceHandlerSendCodeResponse {
  email?: string;
  expires_in?: number;
  message?: string;
}
