/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface InternalInterfaceHandlerTestResponse {
  id?: number;
}
