/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import type { InternalInterfaceHandlerUserResponse } from './internalInterfaceHandlerUserResponse';

export interface InternalInterfaceHandlerLoginResponse {
  access_token?: string;
  expires_in?: number;
  message?: string;
  refresh_token?: string;
  token_type?: string;
  user?: InternalInterfaceHandlerUserResponse;
}
