/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */

export interface InternalInterfaceHandlerRefreshTokenRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  client_id: string;
  refresh_token?: string;
}
