/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import type { InternalInterfaceHandlerUserProfileResponse } from './internalInterfaceHandlerUserProfileResponse';

export interface InternalInterfaceHandlerCreateMyProfileResponse {
  message?: string;
  user_profile?: InternalInterfaceHandlerUserProfileResponse;
}
