FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend/ .

EXPOSE 8080
WORKDIR /app/cmd/server
CMD ["air", "-c", ".air.toml"]