/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
  InternalInterfaceHandlerCreateMyProfileRequest,
  InternalInterfaceHandlerCreateMyProfileResponse
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a user profile for the currently authenticated user. Requires authentication via Bearer token (Authorization header) or HttpOnly cookie (access_token).
 * @summary Create user profile
 */
export const postV1UsersMeProfile = (
    internalInterfaceHandlerCreateMyProfileRequest: InternalInterfaceHandlerCreateMyProfileRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerCreateMyProfileResponse>(
      {url: `/v1/users/me/profile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalInterfaceHandlerCreateMyProfileRequest, signal
    },
      options);
    }
  


export const getPostV1UsersMeProfileMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeProfile>>, TError,{data: InternalInterfaceHandlerCreateMyProfileRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeProfile>>, TError,{data: InternalInterfaceHandlerCreateMyProfileRequest}, TContext> => {

const mutationKey = ['postV1UsersMeProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1UsersMeProfile>>, {data: InternalInterfaceHandlerCreateMyProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1UsersMeProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1UsersMeProfileMutationResult = NonNullable<Awaited<ReturnType<typeof postV1UsersMeProfile>>>
    export type PostV1UsersMeProfileMutationBody = InternalInterfaceHandlerCreateMyProfileRequest
    export type PostV1UsersMeProfileMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Create user profile
 */
export const usePostV1UsersMeProfile = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeProfile>>, TError,{data: InternalInterfaceHandlerCreateMyProfileRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1UsersMeProfile>>,
        TError,
        {data: InternalInterfaceHandlerCreateMyProfileRequest},
        TContext
      > => {

      const mutationOptions = getPostV1UsersMeProfileMutationOptions(options);

      return useMutation(mutationOptions );
    }
    