/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1UserProfilesCheckUsernameParams,
  GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
  InternalInterfaceHandlerCheckUsernameAvailabilityResponse,
  InternalInterfaceHandlerCreateMyProfileResponse,
  _V1MeProfilePostRequest
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a user profile for the currently authenticated user. Requires authentication via Bearer token (Authorization header) or HttpOnly cookie (access_token). Accepts multipart form data with optional icon image file.
 * @summary Create user profile
 */
export const postV1MeProfile = (
    _v1MeProfilePostRequest: _V1MeProfilePostRequest,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`name`, _v1MeProfilePostRequest.name)
formData.append(`username`, _v1MeProfilePostRequest.username)
if(_v1MeProfilePostRequest.icon !== undefined) {
 formData.append(`icon`, _v1MeProfilePostRequest.icon)
 }

      return customAxios<InternalInterfaceHandlerCreateMyProfileResponse>(
      {url: `/v1/me/profile`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getPostV1MeProfileMutationOptions = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1MeProfile>>, TError,{data: _V1MeProfilePostRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1MeProfile>>, TError,{data: _V1MeProfilePostRequest}, TContext> => {

const mutationKey = ['postV1MeProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1MeProfile>>, {data: _V1MeProfilePostRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1MeProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1MeProfileMutationResult = NonNullable<Awaited<ReturnType<typeof postV1MeProfile>>>
    export type PostV1MeProfileMutationBody = _V1MeProfilePostRequest
    export type PostV1MeProfileMutationError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse

    /**
 * @summary Create user profile
 */
export const usePostV1MeProfile = <TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1MeProfile>>, TError,{data: _V1MeProfilePostRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postV1MeProfile>>,
        TError,
        {data: _V1MeProfilePostRequest},
        TContext
      > => {

      const mutationOptions = getPostV1MeProfileMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Checks whether the specified username is available for registration. This endpoint does not require authentication.
 * @summary Check username availability
 */
export const getV1UserProfilesCheckUsername = (
    params: GetV1UserProfilesCheckUsernameParams,
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<InternalInterfaceHandlerCheckUsernameAvailabilityResponse>(
      {url: `/v1/user-profiles/check-username`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetV1UserProfilesCheckUsernameQueryKey = (params?: GetV1UserProfilesCheckUsernameParams,) => {
    return [`/v1/user-profiles/check-username`, ...(params ? [params]: [])] as const;
    }

    
export const getGetV1UserProfilesCheckUsernameQueryOptions = <TData = Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse>(params: GetV1UserProfilesCheckUsernameParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1UserProfilesCheckUsernameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>> = ({ signal }) => getV1UserProfilesCheckUsername(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError, TData> & { queryKey: QueryKey }
}

export type GetV1UserProfilesCheckUsernameQueryResult = NonNullable<Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>>
export type GetV1UserProfilesCheckUsernameQueryError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse


/**
 * @summary Check username availability
 */

export function useGetV1UserProfilesCheckUsername<TData = Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse>(
 params: GetV1UserProfilesCheckUsernameParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetV1UserProfilesCheckUsernameQueryOptions(params,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Check username availability
 */
export const prefetchGetV1UserProfilesCheckUsernameQuery = async <TData = Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError = GithubComKeu5MuzeeBackendInternalHelperErrorResponse | GithubComKeu5MuzeeBackendInternalHelperErrorResponse>(
 queryClient: QueryClient, params: GetV1UserProfilesCheckUsernameParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getV1UserProfilesCheckUsername>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetV1UserProfilesCheckUsernameQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}


