/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Muzee API
 * This is the API documentation for the Muzee application.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSwaggerTest200
} from '.././schemas';

import customAxios from '../../customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Simple test endpoint to verify GitHub Action workflow
 * @summary Test endpoint for Swagger auto-generation
 */
export const getSwaggerTest = (
    
 options?: SecondParameter<typeof customAxios>,signal?: AbortSignal
) => {
      
      
      return customAxios<GetSwaggerTest200>(
      {url: `/swagger-test`, method: 'GET', signal
    },
      options);
    }
  

export const getGetSwaggerTestQueryKey = () => {
    return [`/swagger-test`] as const;
    }

    
export const getGetSwaggerTestQueryOptions = <TData = Awaited<ReturnType<typeof getSwaggerTest>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSwaggerTest>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSwaggerTestQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSwaggerTest>>> = ({ signal }) => getSwaggerTest(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSwaggerTest>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSwaggerTestQueryResult = NonNullable<Awaited<ReturnType<typeof getSwaggerTest>>>
export type GetSwaggerTestQueryError = unknown


/**
 * @summary Test endpoint for Swagger auto-generation
 */

export function useGetSwaggerTest<TData = Awaited<ReturnType<typeof getSwaggerTest>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSwaggerTest>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSwaggerTestQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Test endpoint for Swagger auto-generation
 */
export const prefetchGetSwaggerTestQuery = async <TData = Awaited<ReturnType<typeof getSwaggerTest>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSwaggerTest>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetSwaggerTestQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}


